### ISSUE TITLE
distributed FIleSystem

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#109]
ceph?
GlusterFS

**Comment by pierreozoux** [comment]
Ceph \o/

Nice to read:
http://linux.wiki.allmende.io/view/ceph/view/ceph-cluster/view/setting-up-ceph/view/scope-of-this-ceph-cluster/view/ceph-deployment/view/deploy-ceph-core-components/view/deploy-ceph-user-services

**Comment by pierreozoux** [comment]
http://www.heise.de/newsticker/meldung/Die-Technik-hinter-heise-online-3262514.html

**Comment by almereyda** [comment]
Then also https://www.openstack.org/summit/vancouver-2015/summit-videos/presentation/ceph-at-cern-a-year-in-the-life-of-a-petabyte-scale-block-storage-service
