### ISSUE TITLE
new way to provision DNS/emails

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#116]
Once we have a global etcd:
- watch for new domains added (HOST variable)
- run add_domain.sh script
- add dkim key in etcd 
- update dns based on etcd

**Comment by almereyda** [comment]
Do you use etcd in combination with a multi-host overlay network, like [Kubernetes does with flannel](http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/)?

**Comment by pierreozoux** [comment]
not yet, still far from this dream :)

**Comment by almereyda** [comment]
I believe for DNS a combination of PowerDNS and an interface will be most useful.
- @TeDomum `docker-pdns` - https://github.com/indiehosters/nice-hosting-providers/issues/5#issuecomment-208106107
- @ngoduykhanh `PowerDNS-Admin` - https://github.com/ngoduykhanh/PowerDNS-Admin/issues/16#issuecomment-209677610

---

As we need an email management system which integrates with LDAP, and @ecobytes had chosen @modoboa for this, where it could become interesting to check how the `modoboa-installer` could be misused to bootstrap images for a set of linked containers, probably similar to what Discourse does with its `./launcher`? Especially the last link in https://github.com/tonioo/modoboa/issues/821 to https://github.com/adaline/dockermail seems quite similar to what @IndieHosters have been doing up until now.

**Comment by almereyda** [comment]
To follow up on the sidetracking question above, comparing different overlay networks like tinc or cjdns can be another issue somewhere.

@mrstibbons and me already tried out
- https://arbofaktur.de/node/137.html
- https://arbofaktur.de/blog/raspberry-pi-im-crypto-mesh-teil-2-tinc.html
