### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by nnn-gif** [libresh/libre.sh#125]

**Comment by pierreozoux** [comment]
No there is no WebUI.
And it is not planned anytime soon.
Let's say it will be for the v2 :)

**Comment by nnn-gif** [comment]
what about snicker proxy does it have ui

**Comment by pierreozoux** [comment]
Discontinued, and no webUI

On 10-03-2016 19:34, nicky g wrote:

> what about snicker proxy does it have ui
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/indiehosters/LibrePaaS/issues/125#issuecomment-195012215

## 

I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux
