### ISSUE TITLE
Find a nicer name

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#137]
- librehosting
- librestack
- libre ...

TLDs to consider:
 io, sh, cc

**Comment by almereyda** [comment]
I am voting strongly for LibreStash, transposing into `libresta.sh`.

> [A collection, sometimes hidden; a reserve.](https://en.wiktionary.org/wiki/stash)

**Comment by pierreozoux** [comment]
cc @pbouda @unteem

**Comment by pbouda** [comment]
I like librehosting, I think it's quite clear what it does then.

**Comment by almereyda** [comment]
Sure.

**Comment by pierreozoux** [comment]
In term of domain name, we have:
- libre.host for 625$/an...
- libre.sh for 70$/an

**Comment by almereyda** [comment]
libre.sh !!einself!!111

**Comment by pierreozoux** [comment]
Ok, just bought libre.sh \o/

**Comment by almereyda** [comment]
so it's pronounced 'libreshell' (which I like)?
