### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by almereyda** [libresh/libre.sh#144]
When thinking of cloud orchestration tools or docker maintenance utilities, things like Kubernetes, Rancher, Docker Swarm or Docker Compose come to mind.

Yet we aim at a thin layer, which can work at a single system's level, or in a grid.

Similar projects may be:

* Sandstorm (a bit more user control)
* https://github.com/DFabric/DPlatform-ShellCore
* https://github.com/DFabric/DPlatform-DockerShip

**Comment by JOduMonT** [comment]
FYI: I just add Libre.sh [here](https://selfhosted.libhunt.com/categories/1722-self-hosting-solutions) and [here](http://alternativeto.net/software/libre-sh/)
where you could also find similar project ;)

**Comment by JOduMonT** [comment]
I helped a small organization with http://cloudron.io
It's well done
only problem (for me) it's one domain
but backup and deployment works like a charm.

**Comment by almereyda** [comment]
Thank you for putting our attention at this. I have found the sources in https://git.cloudron.io/cloudron/box and associated application manifests in https://git.cloudron.io/cloudron.

In terms of previous conversation about *migration networks* and documentation and you above stating providing application state alongside such a manifest easily redeploys a given application, I would wonder how we could abstract your data flow for this in terms of applicability to `libre.sh`.

> Indeed your web interface is a start to a community dashboard for federated hosting providers. Are there
>
> 1. different levels of access (role-based access control)
> 2. any plans to extend to meshed container runtimes (similar to mist.io)
>
> ?

I feel having a loosely-coupled interface to a hybrid, multi-datacenter cloud environment with simple community control built in could boost the activities of the https://github.com/indiehosters/awesome-librehosters community.

**Comment by almereyda** [comment]
We have since learned, that:

1. Cloudron ties you to their proprietary store API
https://www.loomio.org/d/QABIXsCG/open-app-ecosystem/5
2. There are also Puffin.rocks and Portainer.io who use similar deployment patterns to libre.sh
https://github.com/indiehosters/libre.sh/pull/159#issuecomment-363872072

**Comment by unteem** [comment]
Closing issue here repo is migrated to [lab.libre.host.st](https://lab.libreho.st/libre.sh/compose.libre.sh)

please follow issue [here](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/144)

**Comment by unteem** [comment]
Closing issue here repo is migrated to [lab.libre.host.st](https://lab.libreho.st/libre.sh/compose.libre.sh)

please follow issue [here](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/144)
