### ISSUE TITLE
Can't update mail settings

### ISSUE THREAD

**Issue by tokelove** [libresh/libre.sh#158]
After deploying to DO using the install instructions, when I try and provision something (for example Wordpress) it uses example@indie.host settings. 

I've tried editing /etc/environment and /libre.sh/user_data with the new details but this unfortunately doesn't work.

**Comment by pierreozoux** [comment]
Arf sorry for the delay, did you manage to fix your issue? I'll close now as this is really old. Please feel free to reopen.
