### ISSUE TITLE
kubernetes migration

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#161]
As k8s is taking over the world, it looks like dumb to continue develop our little hacks for this project.
And nothing stop us to run k8s on a single node.
Plus, the kubernetes ecosystem is more and more mature, and I think it is ready now for us:
 - Flannel has [encryption support](https://github.com/coreos/flannel/pull/898)
 - Rook is [now beta](https://github.com/rook/rook/blob/master/ROADMAP.md) and part of CNCF
 - CoreOS was bought by RedHat so Tectonic will be opensource \o/
 - helm has nice and beautiful helm charts for our loved projects
 - Ingress will replace our HAProxy/nginx hack for the edge
 - Service catalog looks promising to implement service discovery one day (wordpress: "ah, there is ldap, let me use it for user auth :) " ) 

We have all the building blocks to make a beautiful hosting platform  that you can selfhost on baremetal without any cloud provider.

We need to get started somehow.

This is what I feel is the way to go, I'm sure you have other opinions, let me know :)

**Comment by pierreozoux** [comment]
@edr

**Comment by pierreozoux** [comment]
@almereyda @jodumont @niktrix @michielbdejong @niktrix @edrex
I'd love your feedback on this:
 - should we support only hetzner?
 - should we go CoreOS or Debian or Ubuntu?
 - weave or flannel?
 - Rook (ceph) or?
(Is it a strong opinion, or just a recommendation?)

I think that if we are opiniated, the tool would be better and develop faster.
If we are not opiniated, then well, we can also just drop libre.sh and tell people to install kubernetes the way they prefer and we collaborate on the helm packages.

If you know other people that would be interested in this discussion, please ping them :)

**Comment by pierreozoux** [comment]
Ok, so I just played with `hetzner-kube`, it is cool \o/.

I managed to deploy a cluster, add rook \o/ and rocket.chat.
I just didn't manage the tls part, but I know it is doable, I'm tired :)

Here some cryptic notes for the future:
```
$ cat ing-values.yaml 
rbac:
  create: true
controller:
  kind: DaemonSet
  hostNetwork: true
  daemonset:
    useHostPorts: true
$ cat lego-values.yaml 
config:
  LEGO_EMAIL: *
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
rbac:
  create: true
```

**Comment by pierreozoux** [comment]
the discussion continues at https://github.com/xetys/hetzner-kube/issues

**Comment by edrex** [comment]
You mentioned only supporting hetzner. Obviously for US-based folks like me, this isn't a good option. I want to be able to run an IndieHost/LibreHost on a CoreOS/Tectonic cluster deployed to an arbitrary cloud provider or bare metal. I guess others might like to run on GCE. To this end, I'd like to see two things:

 - Discussion leading to a specification for the interface between v.2 LibreHost domain apps and the cluster environment (ingress, dns, storage, etc).
 - The start of a community-edited guide showing how to build a LibreHoster-compliant cluster in various environments.

Thoughts?

**Comment by JOduMonT** [comment]
### Only CoreOS; only Hetzner ?
I don't get the question..  
Also personally I don't use the libre.sh  It's nice project but others projects like Cloudron do so much more, which BTW I don't use too ;)

#### So what I'm doing here ?
I respect the idea and love the initiative; and I'm sorry for the kitten (chatons) but I think, we play in another category here, which is fine because Framasoft never said they will be professional and their primary goal is to do mediatization and education around GAFAM alternatives. And also; Libre sh help to be start with docker.  I still use, in a way the haproxy :)

#### Hetzner in US ?
@edrex OVH offer container for everyone : https://labs.ovh.com and they open datacenters in US.  

## Security perspective  
- Now ContainerOS, aka CoreOS is a RedHat product which means they will definitely push for SELinux, besides the other major player RancherOS also use SELinux.  
- Debian/Ubuntu focus more on AppArmor but also support SELinux  

## Who is the target ?
- SOHO and SMEs will definitely go with Debian/Ubuntu  
- Bigger enterprise and NGO will opt for RedHat because they are might need to comply with guidance and checklist.

**Comment by pierreozoux** [comment]
@edrex @jodumont I heard you! Thanks for the valuable feedback!

I start the migration now!

All libre.sh v1 repo related to docker-compose will be deprecated, and moved to git.indie.host.
(If anybody want to takeover ownership, and continue this project, I'm fine with it too :) )
The migration will last for some months, so we'll continue the support for us during this period of time.

Regarding kubernetes, the goal will be to collaborate, there are already a lot of places to collaborate, especially: https://github.com/kubernetes/charts/

Then, I think this repo will just be documentation on how to install kubernetes in what we consider the reference implementation. This will be splitted in 2 parts:
 - install kubernetes (hetzner-kube, tectonic...) links to documentation, or how we install it ourself.
 - install libre.sh on top (an opinionated vision on what to use for network, disks, monitoring, dns..)

I guess it will just become documentation, and collaboration will happen in other repos, but let's see!

**Comment by edrex** [comment]
Thanks for the update Pierre. I am interested in running indiehoster
clusters in:

 - Tectnonic/CoreOS clusters, both cloud and on prem.
 - Potentially also AArch64/armv8-based on-prem clusters with something
like Espressobin boards
http://linuxgizmos.com/39-dollar-network-switching-pico-itx-sbc-packs-dual-core-cortex-a53/

I will try to keep up with the techniques and conventions you are
leveraging in the reference implementation, and contribute guides for those
platforms where I am operating.

**Comment by edrex** [comment]
Those boards actually wouldn't make good compute nodes since they only have two cores, still looking around for the right hardware.
