### ISSUE TITLE
Rename organisation?

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#162]
@almereyda expressed the interest to rename this organisation.
Myself I always found confusing that the name of the network (IndieHosters) and the name of the first hoster (indie.host) is the same.

I think I'm ready to rename it to allow broader collaboration and better governance.

@jodumont @almereyda @unteem @edrex
I'd like your opinion on this supposition.

Then for the name, it looks natural to use LibreHosters.
What do you think?
Then a hoster using libre.sh is a LibreHoster.
And we can also rename our hoster list to just awesome-hosters.
(As they are awesome because using libre software)
Or maybe you have better ideas?

**Comment by edrex** [comment]
I like the name LibreHosters. I was initially confused about the relation between organization managing the tools, and the particular network IndieHosters.

**Comment by pierreozoux** [comment]
Ok, the switch happened!

There is the hoster: https://indie.host
There is the network, it is starting:
https://github.com/libresh/awesome-librehosters
and a matrix channel!
#librehosters:chat.weho.st

And the tool itself: http://libre.sh with the reboot:
https://pad.lamyne.org/GwRghgJhBGDMCcBaAxtNiAs9pkfVA7IgKzTEZgAMAZvGNJcEA===?view#the-technical-bits
