### ISSUE TITLE
Sync between gitlab and github

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#164]
Currently, the project is a bit in between.
https://git.indie.host/meta/

And I really think it is bad for the community.

We need to figure out a good solution for people to be able to contribute on GitHub or GitLab as easily.

The best way would be to have push/pull sync, but it is a GitLab EE feature.
And syncing issues/comments/PR from GitHub to GitLab would also be nice to have.

With the move to #161 I'm actually wondering how much custom things we'll need.

And as a final note, it is a lot of effort to maintain this.
I'm actually doubting.

In one hand, I want people to contribute as easy as possible.
In the other hand, I don't want to force any contributor to create a GitHub account.

**Comment by JOduMonT** [comment]
_First of all; I'm definitely not the most advance git user of the world but this might help in the reflexion._

#### Prelude
1. I understand the move to a private gitlab; such as an example [cloudron](https://git.cloudron.io) only use a private gitlab.  
2. I also understand it make less exposure for the project and that why you came with this question.  
3. Also, for what I understand and which is make sense for me, Git is designed to have only one central point, at one point you need to converge ;)

#### ~~Webhook~~
Temporary it possible to make webhook to sync bi-directionnaly gitlab and github but it's not viable as you must know.

#### 2 Destinations ?
I never try but It's possible to have [two destination](https://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes)

#### Submodules ?
It's also, as you must know, possible to integrate another git into a git via submodule. Maybe github could be a sub git of gitlab or vice et versa

#### Branch ?
Maybe github could be a branch and in gitlab you make a team to test, review and approve it

**Comment by pierreozoux** [comment]
Thanks @jodumont for the input, but we need one place for code ok, but for issues and project too...

I prefer keeping it on GitHub first actually, if somebody wants to PR, and don't want to touch GitHub, they can send patch by email!

I'll move libre.sh v1 to GitLab and keep libre.sh v2 on GitHub.
