### ISSUE TITLE
Backup whithout sftp

### ISSUE THREAD

**Issue by lalop** [libresh/libre.sh#167]
It seems that, the current setup can only baackup using sftp.
Is there a reason why the protocole doesn't appear in the BACKUP_DESTINATION ?
Like that we can use any of the duplicity protocole.
Hubic or amazon can be cheapest than a bare metal server for backup, do you see any reason why don't use them ?

**Comment by pierreozoux** [comment]
Actually.. Now we use borg:
https://git.indie.host/meta/borg-server/
https://git.indie.host/meta/borg-client/
https://github.com/indiehosters/docker-borg/

If you have any question about anytthing, please ask, I probably already thought about it :)

I'll close here, or we need to rename to update the status.

**Comment by lalop** [comment]
So [indiehosters/backups](https://github.com/indiehosters/backups), [indiehosters/pull-backups](https://github.com/indiehosters/pull-backups), [indiehosters/sshd-backups](https://github.com/indiehosters/sshd-backups) and [indiehosters/docker-backups](https://github.com/indiehosters/docker-backups) are deprecated ?

**Comment by pierreozoux** [comment]
yeah kind of, sorry.

It still probably work, but nowaday, I prefer borg, it is a lot more efficient.

**Comment by lalop** [comment]
If this is the case maybe this should be explicit, by adding a `[deprecated]` in description and maybe moving them to a specific group in github/gitlab to help finding the good repositories.

And what about `BACKUP_DESTINATION` ? Is it used by borg setup ?

**Comment by JOduMonT** [comment]
@lalop You might want to give a try to : https://github.com/linuxserver/docker-duplicati/
it a webinterface for Duplicati and will allow you to choose Hubic as a destination

**Comment by pierreozoux** [comment]
Ok, will close the issue for now, feel free to re-open if needed.
