### ISSUE TITLE
setting up new app

### ISSUE THREAD

**Issue by albjeremias** [libresh/libre.sh#169]
Hi!!
Im trying to use this tool, for installing my docker-compose stuff... 
here: https://framagit.org/c1000101/Docker-coletivos

but I get this error after running:
```$ libre update```
```
systemctl restart system
Docker-coletivos
s@Docker-coletivos
Failed to restart system.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status system.service' for details.
Failed to restart Docker-coletivos.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status Docker-coletivos.service' for details.
Failed to restart s@Docker-coletivos.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status s@Docker-coletivos.service' for details.
```

**Comment by albjeremias** [comment]
ok fixed... need to run systemctl as root or sudo...

```
$ libre provision -a git@framagit.org:c1000101/Docker-coletivos.git  -u libre.coletivos.org
Cloning into '/data/domains/libre.coletivos.org'...
fatal: unable to access 'https://git@framagit.org:c1000101/Docker-coletivos.git.git/': Illegal port number
```
which port?? from framagit?

**Comment by albjeremias** [comment]
when running libre without parameters will have this!
```$ libre
/live/instances/libre.sh/utils/libre: line 34: $1: unbound variable
``` 

// I will do a PR with fixes for all of this.. I already fixed the above also! https://github.com/libresh/libre.sh/blob/master/utils/provision#L106 this is a bit hardcoded...

**Comment by pierreozoux** [comment]
Yes, `libre` has to be run as root.

the `package` format is in the https form: `framagit.org/c1000101/Docker-coletivos`

we can handle better errors when there is no arguments.

Feel free to PR or adjust the documentation.

**Comment by pierreozoux** [comment]
I think all your issues were addressed, closing for now, feel free to re-open!
