### ISSUE TITLE
Handle git branches when provisioning 

### ISSUE THREAD

**Issue by freechelmi** [libresh/libre.sh#174]
Currently the provision command can only clone a repo and use it as is.

This is not enough for production where you want a test , staging & live branch 

So provision would need a new parameter to target a tag or branch for the git repo.

**Comment by unteem** [comment]
Closing issue here repo is migrated to [lab.libre.host.st](https://lab.libreho.st/libre.sh/compose.libre.sh)

please follow issue [here](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/174)
