### ISSUE TITLE
Maintenance command for web services

### ISSUE THREAD

**Issue by almereyda** [libresh/libre.sh#175]
When caring for services, at times their web presence is disabled for maintenance reasons. A repeating pattern is:

```
libre stop
libre disable
vim docker-compose.yml
docker-compose up -d
docker-compose stop
vim docker-compose.yml
docker-compose up -d
docker-compose stop
libre enable
libre start
```

It could be nice to map maintenance pages on those services exposing a web frontend via a simple

    libre maintenance

to toggle between the states.

**Comment by pierreozoux** [comment]
Indeed!  I think it would.be 5 lines of code, you just need an nginx container with your maintenance page.

Libre maintenance start

Libre stop
Docker run --name current dir -e virtual-host=current dir maintenance

Libre maintenance stop

Docker stop current dir
Libre start

(Sorry On mobile)

**Comment by pierreozoux** [comment]
Do you have this maintenance image? And do you plan to do that in the coming week ? If not I'll just close the issue, and you PR when you have the code

**Comment by unteem** [comment]
Closing issue here repo is migrated to [lab.libre.host.st](https://lab.libreho.st/libre.sh/compose.libre.sh)

please follow issue [here](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/175)
