### ISSUE TITLE
[v1] Need proper way to delete a service 

### ISSUE THREAD

**Issue by freechelmi** [libresh/libre.sh#176]
Right now there is no command to delete a libre.sh website properly.

We need to : 

- delete the directory 
- remove the systemd service

**Comment by pierreozoux** [comment]
Ideally you want to.delete the cert from haproxy too, there is already some code there

**Comment by freechelmi** [comment]
Yes But I'd prefer that the haproxy cert gets deleted automagically as soon as the corresponding container does not exists anymore ( mabe for a given significant period like few days)

**Comment by pierreozoux** [comment]
@freechelmi can you check the PR please?

**Comment by unteem** [comment]
Closing issue here repo is migrated to [lab.libre.host.st](https://lab.libreho.st/libre.sh/compose.libre.sh)

please follow issue [here](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/176)
