### ISSUE TITLE
Needs more documentation on operation

### ISSUE THREAD

**Issue by cfra** [libresh/libre.sh#178]
I have just installed a CoreOS machine with the provided userdata. However, apart from an `lb_web` docker network being created and some services and tools being installed, not much has happened yet.

Some of the tools also do not work yet, because they expect some API at `${cloud_hostname}` and `${mail_hostname}`. These variables are not defined in the example installation. Also, it is unclear to me which services would provide these APIs.

I am completely at a loss how I should continue the setup. My impression is that I would add applications with `libre provision`, and these applications would probbaly be `compose-*` packages from your github project.

However, I have no idea how the web ingress is supposed to work, how I setup mail, or how I configure domain names in the first place.

If somebody could guide me through that, I would also be willing to take a stab at writing some documentation.

**Comment by pierreozoux** [comment]
Hello, and welcome here :)

You can also come to our chat: https://riot.allmende.io/#/room/#libre.sh:matrix.allmende.io
Where have you heard about libre.sh ? Just curious :)

Once you completed the setup, indeed, there is still some work.

1. you need to choose an https load balancer.
I personally use Haproxy (the one listed in the readme), but some people prefer nginx.
Feel free to use either and report which one was easier to use :)

2. for email, yes, it is another `compose` file here: https://github.com/libresh/compose-email
It should work, although I installed just once, so it might rough on the edges, and you don't necessarily need it to run your server.

The provision script indeed works well with email, as it creates an email address for the services, but you can also do it by hand.

About emails, we are exploring mailu also, and I think you'll have a lot better experience wiht them!

Also, we are moving everyhting there:
https://lab.libreho.st/libre.sh/compose

All the repos are no there, and I havve to fix GitHub. Just this repo is the last one to be moved, I'll try to communicate about it.

Feel free to come to the chat, it would be easier ;)

(I'll close, but continue to comment :) )
