### ISSUE TITLE
Add in house monitoring

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#24]
http://www.redotheweb.com/uptime/

and integrate with provision script

**Comment by pierreozoux** [comment]
http://www.slideshare.net/BrianChristner/2015-dockecon-monitoring-presentation

http://www.infoq.com/news/2015/12/dockercon-docker-monitoring?utm_source=hacker%20news&amp;utm_medium=link&amp;utm_campaign=external

https://www.brianchristner.io/how-to-setup-docker-monitoring/

**Comment by almereyda** [comment]
http://prometheus.io/, InfluxDB and Graphana should be enough for inhouse monitoring. But reporting services uptime seems another topic.

Also see https://github.com/debops/ansible-librenms

**Comment by pierreozoux** [comment]
Yes, I digged a bit more on the subject, and prometheus seems like a nice option.

I'm thinking about https://github.com/firehol/netdata/issues/318 too :) Looks like a lot simpler, and they are about to add alerting!

**Comment by pierreozoux** [comment]
But yeah, actually, we still need log coolection, we need to setup alert on those logs. And we'll also need uptime monitoring.

I opened 4 different issues for that.
