### ISSUE TITLE
unterminated string in sed statement

### ISSUE THREAD

**Issue by michielbdejong** [libresh/libre.sh#47]
Maybe you need to escape the spaces here:

```
+ cat /home/michiel/indiehosters/indiepaas/scripts/../configs/server.config
+ sed s/##BACKUP_IP##/107.191.46.27 107.191.63.235 108.61.209.235/g
sed: -e expression #1, char 29: unterminated `s' command
```

**Comment by michielbdejong** [comment]
Ah ok,  I see what happened, it's when there were multiple attempts, not all followed by stop.sh.

**Comment by michielbdejong** [comment]
After each half-failed attempt, you need to:
- remove the servers on vultr
- remove the lines from /etc/hosts
- run  `sudo ssh-keygen -f "/root/.ssh/known_hosts" -R backup.test`
- run  `sudo ssh-keygen -f "/root/.ssh/known_hosts" -R server.test`

Otherwise the new attempt will fail again.

Worth mentioning that in the readme!

**Comment by pierreozoux** [comment]
If you run `scripts/stop.sh` it should be fine. (But you have to wait at least 5mins)

There should be no failed attempt :)
