### ISSUE TITLE
internal server error on https://owncloud.test/

### ISSUE THREAD

**Issue by michielbdejong** [libresh/libre.sh#53]
when trying to open https://owncloud.test/, I see "internal server error". The logs just show:

```
"GET / HTTP/1.1" 500 2828 "-" "Mozilla/5.0 
```

(I checked both `docker logs owncloud.test` and `journalctl -u web@owncloud.test`)

**Comment by michielbdejong** [comment]
This is before having run [the reboot step](https://github.com/IndiePaaS/IndiePaaS/blob/master/README.md#start-tests) by the way, not sure if that's relevant.

**Comment by pierreozoux** [comment]
Actually the reboot step is just to test also after a reboot :) As the server might be able to reboot at any time, it should reboot without any stress.

**Comment by pierreozoux** [comment]
fixed as of cdee9b3
