### ISSUE TITLE
Add DNS server

### ISSUE THREAD

**Issue by pierreozoux** [libresh/libre.sh#98]
https://github.com/PowerDNS/pdns

**Comment by almereyda** [comment]
Check https://github.com/obi12341/docker-pdns + https://github.com/xbgmsharp/yapdnsui, via https://github.com/PowerDNS/pdns/wiki/WebFrontends

**Comment by almereyda** [comment]
@TeDomum uses https://github.com/TeDomum/docker-pdnscontrol

**Comment by almereyda** [comment]
Also check out https://github.com/ngoduykhanh/PowerDNS-Admin/issues/16#issuecomment-209677610

**Comment by almereyda** [comment]
Plus http://ralph-ng.readthedocs.org/en/latest/user/domains/

**Comment by pierreozoux** [comment]
The DNS issue is here :)

I'd love to have DNS server, but this needs to be addressed after https://github.com/indiehosters/LibrePaaS/issues?milestone=5

But yeah, the advantage of PowerDNS is the API.

**Comment by dolanor** [comment]
Have you checked CoreDNS also ? Could be interesting.
